#!/bin/env python 
# Start the Fu umount watcher daemon
#
# chkconfig: 2345 82 17
# description: Monitors for FU umount in FFF appliance
# processname: fffumountwatcher
# pidfile: /var/run/fffumountwatcher.pid
### BEGIN INIT INFO
# Provides: fffumountwatcher
# Required-Start: $syslog $local_fs messagebus
# Required-Stop: $syslog $local_fs
# Default-Stop: 0 1 6
# Default-Start: 2 3 5
# Short-Description: Blah
# Description: Saves Blah2
### END INIT INFO

import procname
import os,sys,time
import subprocess
sys.path.append('/opt/fff')
from applianceumount import *

if len(sys.argv)==1:
  #sys.argv=sys.argv[0]
  procname.setprocname('fffumountwatcher')
  start()
#  sys.exit(0)

elif sys.argv[1]=='start' or sys.argv[1]=='restart':
#  p = subprocess.Popen("/etc/init.d/fffumountwatcher", shell=True, stdout=subprocess.PIPE)
#  p.wait()
#  sys.argv=sys.argv[0]
  procname.setprocname('fffumountwatcher')
  start()

elif sys.argv[1]=='stop':
  print "stopping"
  time.sleep(10)
  stop()
elif sys.argv[1]=='status':
  status()
