#!/bin/env python
#
# chkconfig:   2345 81 03
#
import os,sys
sys.path.append('/opt/hltd/python')
sys.path.append('/opt/hltd/lib')
from hltd import hltd
from subprocess import Popen
from subprocess import PIPE
from applianceumount import stopFUs
import time
import syslog

def touchLockFile():
    try:
        with open('/var/lock/subsys/hltd',"w+") as fi:
            pass
    except:
        pass

def removeLockFile():
    try:
        os.unlink('/var/lock/subsys/hltd')
    except:
        pass

if __name__ == "__main__":
    daemon = hltd('/var/run/hltd.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            touchLockFile()
            output = Popen(["/opt/hltd/python/hltd.py"], stdout=PIPE).communicate()[0]
            if daemon.silentStatus():
                print '[OK]'
            else:
                print '[Failed]'
                print output
        elif 'stop' == sys.argv[1]:
            if daemon.status():
                daemon.stop()
            elif os.path.exists('/var/run/hltd.pid'):
                daemon.delpid()

            #determine runlevel
            p = Popen("runlevel", shell=True, stdout=PIPE)
            p.wait()
            std_out=p.stdout.read()
            from_level,to_level = std_out.split('\t')[0].rstrip('\n').strip().split(' ')
            if to_level.isdigit() and int(to_level) in [0,1,6] and str(from_level)!="1":
 
                if stopFUs()==False:
                    msg = "Shutdown or reboot is cancelled by hltd - FU umount failed! Switching to runlevel 3..."
                    syslog.syslog(msg)
                    time.sleep(2)
                    p = Popen("init 3", shell=True, stdout=PIPE)
                    p.wait()
                else:
                    removeLockFile()
            else:
                print "Lock file remains. Run stop-appliance to unmount FUs."

        elif 'stop-appliance' == sys.argv[1]:
            if daemon.status():
                daemon.stop()
            elif os.path.exists('/var/run/hltd.pid'):
                daemon.delpid()

            if stopFUs()==False:
                print "FU umount failed, lock file remains. FU umount failed"
            else:
                removeLockFile()

        elif 'stop-light' == sys.argv[1]:
            if daemon.status():
                daemon.stop()
            elif os.path.exists('/var/run/hltd.pid'):
                daemon.delpid()
            removeLockFile()
 
        elif 'restart' == sys.argv[1]:
            daemon.restart()
            touchLockFile()
        elif 'status' == sys.argv[1]:
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
#        print "hltd "+sys.argv[1]+"ed"
#        logging.debug("executed "+sys.argv[1])
        sys.exit(0)

    else:
        print "usage: %s start|stop|stop-light|restart|status" % sys.argv[0]
        sys.exit(2)
